const groupsByType = [
  {
    CODIGO: '0010',
    DESCRICAO: 'ROMPEDOR EDT',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0020',
    DESCRICAO: 'ROMPEDOR LPG',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0030',
    DESCRICAO: 'ROMPEDOR AGF',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0040',
    DESCRICAO: 'ROMPEDOR USADO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0050',
    DESCRICAO: 'VIBRO RIPPER',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0060',
    DESCRICAO: 'TREVI BENNE',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0070',
    DESCRICAO: 'VTN',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0080',
    DESCRICAO: 'ACESSORIO DE MINI CARREGADEIRA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0090',
    DESCRICAO: 'SOCOMEC',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0091',
    DESCRICAO: 'EDIL GRAPA E IMA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0092',
    DESCRICAO: 'ROCK TOOLS',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0093',
    DESCRICAO: 'EURO IMPLEMENTOS',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0094',
    DESCRICAO: 'ARRASADOR DE ESTACA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0095',
    DESCRICAO: 'ENGATE RAPIDO E SUPORTE',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0097',
    DESCRICAO: 'BALANCAS RDS',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0110',
    DESCRICAO: 'MAQUINAS E EQUIPAMENTOS USADOS / REMANUFATURADOS',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0120',
    DESCRICAO: 'BOMBA HDRAULICA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0130',
    DESCRICAO: 'PECAS REPOSICAO BOMBA HIDRAULI',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0200',
    DESCRICAO: 'KIT HIDRAULICO RETRO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0201',
    DESCRICAO: 'KIT HIDRAULICO ESCAVADEIRA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0202',
    DESCRICAO: 'KIT HIDRAULICO PARTES',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0203',
    DESCRICAO: 'KIT LUBRIFICACAO AUTOMATICA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0204',
    DESCRICAO: 'KIT HIDRAULICO BRANQUEADORA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0300',
    DESCRICAO: 'PECAS DE REPOSICAO ROMPEDOR',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0301',
    DESCRICAO: 'PECAS REP ROMPEDOR NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0350',
    DESCRICAO: 'PECAS DE REPOSICAO VTN',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0360',
    DESCRICAO: 'PECAS DE REPOSICAO GF GORDINI',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0370',
    DESCRICAO: 'PECAS DE REPOSICAO ROCK TOOLS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0375',
    DESCRICAO: 'PECAS ARRASADOR DE ESTACA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0380',
    DESCRICAO: 'PECAS DE REPOSICAO SOCOMEC',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0390',
    DESCRICAO: 'PECAS DE REPOSICAO DAEDONG',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0400',
    DESCRICAO: 'PECAS DE REPOSICAO TREVI',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0401',
    DESCRICAO: 'FACAS NACIONAIS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0490',
    DESCRICAO: 'PECAS DE REPOSICAO OUTRAS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0500',
    DESCRICAO: 'GERADOR',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0501',
    DESCRICAO: 'COMPACTADOR',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0502',
    DESCRICAO: 'ENGATE RAPIDO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0503',
    DESCRICAO: 'TRAVESSEIRO PNEUMATICO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0504',
    DESCRICAO: 'PULVERIZADOR',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0505',
    DESCRICAO: 'CONCHA SELECIONADORA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0510',
    DESCRICAO: 'MAQUINA FIO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0520',
    DESCRICAO: 'FUNDO FURO / BANQUEADORA',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0530',
    DESCRICAO: 'MINDRILL',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0540',
    DESCRICAO: 'FRESADORA DE ASFALTO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0550',
    DESCRICAO: 'COMPRESSOR',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0560',
    DESCRICAO: 'BRACO HIDRAULICO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0570',
    DESCRICAO: 'MULTIFIO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0580',
    DESCRICAO: 'FAMILIA POLIMENTO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '0590',
    DESCRICAO: 'PRODUTOS INTERMEDIARIOS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0591',
    DESCRICAO: 'INTERMEDIARIOS CALDEIRARIA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0592',
    DESCRICAO: 'INTERMEDIARIOS USINAGEM',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0593',
    DESCRICAO: 'INTERMEDIARIOS PINTURA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0594',
    DESCRICAO: 'INTERMEDIARIOS MONTAGEM',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0595',
    DESCRICAO: 'INTERMEDIARIOS EXTERNOS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0596',
    DESCRICAO: 'INTERMEDIARIOS ELETRICA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0800',
    DESCRICAO: 'PECAS DE REPOSICAO NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0801',
    DESCRICAO: 'PECAS REP ROMPEDOR NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0802',
    DESCRICAO: 'PECAS REPOSICAO BOMBA HIDRAULICA NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0803',
    DESCRICAO: 'PECAS DE REPOSICAO VTN NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0804',
    DESCRICAO: 'PECAS DE REPOSICAO GF GORDINI NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0805',
    DESCRICAO: 'PECAS DE REPOSICAO ROCK TOOLS NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0806',
    DESCRICAO: 'PECAS ARRASADOR DE ESTACA NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0807',
    DESCRICAO: 'PECAS DE REPOSICAO SOCOMEC NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0808',
    DESCRICAO: 'PECAS DE REPOSICAO DAEDONG NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0809',
    DESCRICAO: 'PECAS DE REPOSICAO TREVI NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0810',
    DESCRICAO: 'FACAS NACIONAIS NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0811',
    DESCRICAO: 'PECA REPOSICAO MINDRILL NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0812',
    DESCRICAO: 'PECA REPOSICAO MAQUINA FIO NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0813',
    DESCRICAO: 'PECA REPOS.FUNDO FURO/BANQUEADORA NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0814',
    DESCRICAO: 'PECA DE REPOSICAO GERADORES NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0815',
    DESCRICAO: 'PECAS DE REPOSICAO COMPRESSOR NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0816',
    DESCRICAO: 'PECAS DE REPOSICAO MULTIFIO NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0817',
    DESCRICAO: 'PECAS DE REPOSICAO IMPLEMENTOS DE MINI CARREGADEIRA NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0818',
    DESCRICAO: 'PECAS DE REPOSICAO BRACO HIDRAULICO NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0819',
    DESCRICAO: 'PECAS DE REPOSICAO LINHA DE POLIMENTO NACIONAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0899',
    DESCRICAO: 'NACIONAL SOBRE DEMANDA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0900',
    DESCRICAO: 'PECAS DE REPOSICAO IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0901',
    DESCRICAO: 'PECAS DE REPOSICAO ROMPEDOR IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0902',
    DESCRICAO: 'PECAS REPOSICAO BOMBA HIDRAULICA IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0903',
    DESCRICAO: 'PECAS DE REPOSICAO VTN IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0904',
    DESCRICAO: 'PECAS DE REPOSICAO GF GORDINI IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0905',
    DESCRICAO: 'PECAS DE REPOSICAO ROCK TOOLS IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0906',
    DESCRICAO: 'PECAS ARRASADOR DE ESTACA IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0907',
    DESCRICAO: 'PECAS DE REPOSICAO SOCOMEC IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0908',
    DESCRICAO: 'PECAS DE REPOSICAO DAEDONG IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0909',
    DESCRICAO: 'PECAS DE REPOSICAO TREVI IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0910',
    DESCRICAO: 'FACAS IMPORTADO IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0911',
    DESCRICAO: 'PECA REPOSICAO MINDRILL IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0912',
    DESCRICAO: 'PECA REPOSICAO MAQUINA FIO IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0913',
    DESCRICAO: 'PECA REPOS.FUNDO FURO/BANQUEADORA IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0914',
    DESCRICAO: 'PECA DE REPOSICAO GERADORES IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0915',
    DESCRICAO: 'PECAS DE REPOSICAO COMPRESSOR IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0916',
    DESCRICAO: 'PECAS DE REPOSICAO MULTIFIO IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0917',
    DESCRICAO: 'PECAS DE REPOSICAO IMPLEMENTOS DE MINICARREGADEIRA IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0918',
    DESCRICAO: 'PECAS DE REPOSICAO BRACO HIDRAULICO IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0919',
    DESCRICAO: 'PECAS DE REPOSICAO LINHA DE POLIMENTO IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '0999',
    DESCRICAO: 'IMPORTADO SOBRE DEMANDA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3000',
    DESCRICAO: 'MP ROCHAS ORNAMENTAIS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3030',
    DESCRICAO: 'MP MATERIAL ELETRICO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3031',
    DESCRICAO: 'CABOS ELETRICOS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3032',
    DESCRICAO: 'MP IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3033',
    DESCRICAO: 'INVERSORES',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3034',
    DESCRICAO: 'MOTORES',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3035',
    DESCRICAO: 'ALTERNADORES',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3040',
    DESCRICAO: 'OXICORTE POR PONTO DE PEDIDO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3041',
    DESCRICAO: 'MP OXICORTE',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3042',
    DESCRICAO: 'PECAS DE PLASTICO / NYLON',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3043',
    DESCRICAO: 'OXICORTE AVULSO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3044',
    DESCRICAO: 'MP FABRICACAO CILINDROS HIDRAULICOS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3050',
    DESCRICAO: 'MP ACO CHAPAS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3060',
    DESCRICAO: 'MP ACO TUBOS, BARRAS ETC',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3099',
    DESCRICAO: 'MP KIT HIDRAULICO MINIMO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3100',
    DESCRICAO: 'MATERIAS PRIMAS GENERICAS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3200',
    DESCRICAO: 'MP PARAFUSOS PORCAS E ARRUELAS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3210',
    DESCRICAO: 'MP CONEXOES',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3211',
    DESCRICAO: 'MP CONEXOES - EXCECAO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3220',
    DESCRICAO: 'MP CHAPARIA KIT HIDRAULICO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3230',
    DESCRICAO: 'MP VALVULA BRACADEIRA E OUTROS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3240',
    DESCRICAO: 'MP TUBOS E MANGUEIRAS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3250',
    DESCRICAO: 'MP KIT HIDRAULICO IMPORTADO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3300',
    DESCRICAO: 'CONSUMIVEIS PRODUCAO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3301',
    DESCRICAO: 'CONSUMIVEIS SOB DEMANDA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3302',
    DESCRICAO: 'CONSUMIVEIS SEGURANCA - EPIS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3303',
    DESCRICAO: 'CONSUMIVEIS USINAGEM',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3304',
    DESCRICAO: 'CONSUMIVEIS SOLDA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3305',
    DESCRICAO: 'CONSUMIVEIS PINTURA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3306',
    DESCRICAO: 'CONSUMIVEIS LOGISTICA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3307',
    DESCRICAO: 'FERRAMENTAS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3308',
    DESCRICAO: 'MANUTENCAO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3400',
    DESCRICAO: 'MP IMPLEMENTOS MINI CARREG',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3500',
    DESCRICAO: 'MP GERADOR',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3501',
    DESCRICAO: 'MP MAQUINAS LINHA DE POLIMENTO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3510',
    DESCRICAO: 'MP BRACO HIDRAULICO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3550',
    DESCRICAO: 'MP COMPRESSOR',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '3600',
    DESCRICAO: 'MP ARRASADOR DE ESTACA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '5000',
    DESCRICAO: 'SERVICOS E LOCACOES RENTAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '5100',
    DESCRICAO: 'SERVICO DE ASSISTENCIA TECNICA',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '9000',
    DESCRICAO: 'ATIVO IMOBILIZADO',
    TIPO: 'EQUIPAMENTO'
  },
  {
    CODIGO: '9050',
    DESCRICAO: 'MAT DE MANUT DE MAQ RENTAL',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '9100',
    DESCRICAO: 'MAT. DE USO E CONSUMO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '9150',
    DESCRICAO: 'MATERIAIS DIVERSOS',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '9200',
    DESCRICAO: 'PRODUTOS DIVERSOS ADM',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '9210',
    DESCRICAO: 'UNIFORMES',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '9250',
    DESCRICAO: 'SERV INDUSTR/BENEFICIAMENTO',
    TIPO: 'PEÇAS'
  },
  {
    CODIGO: '9999',
    DESCRICAO: 'PRODUTO AGUARDANDO INFORMACOES',
    TIPO: 'PEÇAS'
  }
]

module.exports = { groupsByType }
