module.exports = {
  async index(_, res) {
    return res.json({
      refresh: 0,
      items: [
        {
          number: '200',
          name: 'Portaria',
          firstname: 'Bruno',
          lastname: 'Sossai',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '201',
          name: 'RH / Seg. Trabalho',
          firstname: 'Mariá / Maitê',
          lastname: '',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '203',
          name: 'Marketing',
          firstname: 'Yuri',
          lastname: 'Victor',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '204',
          name: 'Gerência TI',
          firstname: 'Arthur',
          lastname: 'Pedroti',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '205',
          name: 'TI',
          firstname: 'Kevin / Ronaldo',
          lastname: '',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '206',
          name: 'Elétrica',
          firstname: 'Deolindo',
          lastname: 'Arcanjo',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '250',
          name: 'Gerência Logística',
          firstname: 'Gilson',
          lastname: 'Ribeiro',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '251',
          name: 'PCP',
          firstname: 'Guilherme / Emily',
          lastname: '',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '253',
          name: 'Imp & Exp',
          firstname: 'Jean',
          lastname: 'Vieira',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        },
        {
          number: '260',
          name: 'Genrência Fin / Contabilidade',
          firstname: 'Mayara / Jonata',
          lastname: '',
          phone: '',
          mobile: '',
          email: '',
          address: '',
          city: '',
          state: '',
          zip: '',
          comment: '',
          presence: 0,
          starred: 0,
          info: ''
        }
      ]
    })
  }
}
