const express = require('express')
const routes = express.Router()

const EstoqueController = require('./controllers/EstoqueController')
const PCsController = require('./controllers/PCsController')
const SCsController = require('./controllers/SCsController')
const EmpController = require('./controllers/EmpController')
const OuController = require('./controllers/OuController')
const OPsController = require('./controllers/OPsController')
const OPCostsController = require('./controllers/OPCostsController')
const RegisterController = require('./controllers/RegisterController')
const ProductController = require('./controllers/ProductController')
const ClientController = require('./controllers/ClientController')
const FatController = require('./controllers/FatController')
const AverageController = require('./controllers/AverageController')
const InputDocsController = require('./controllers/InputDocsController')
const PriceController = require('./controllers/PriceController')
const PcGroupedController = require('./controllers/PcGroupedController')
const BranchContactsController = require('./controllers/BranchContactsController')
const KardexController = require('./controllers/KardexController')
const CdeBudgetController = require('./controllers/CdeBudgetController')
const DefaultersController = require('./controllers/DefaultersController')
const FatGroupedByStateController = require('./controllers/FatGroupedByStateController')
const FatGroupedBySellerController = require('./controllers/FatGroupedBySellerController')
const ReportClientController = require('./controllers/ReportClientController')

routes.get('/estoques', EstoqueController.index)
routes.get('/pcs', PCsController.index)
routes.get('/scs', SCsController.index)
routes.get('/emp', EmpController.index)
routes.get('/ou', OuController.index)
routes.get('/ops', OPsController.index)
routes.get('/op-costs', OPCostsController.index)
routes.get('/register', RegisterController.index)
routes.get('/products', ProductController.index)
routes.get('/clients', ClientController.index)
routes.get('/fat', FatController.index)
routes.get('/average', AverageController.index)
routes.get('/inputdocs', InputDocsController.index)
routes.get('/price', PriceController.index)
routes.get('/purchases-grouped', PcGroupedController.index)
routes.get('/branch-contacts', BranchContactsController.index)
routes.get('/kardex', KardexController.index)
routes.get('/cdebudget', CdeBudgetController.index)
routes.get('/group-fat-state', FatGroupedByStateController.index)
routes.get('/group-fat-seller', FatGroupedBySellerController.index)
routes.get('/defaulters', DefaultersController.index)
routes.get('/reportclient', ReportClientController.index)

module.exports = routes
